name: CI — Production

on:
  push:
    branches: [production]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Toolchain and Environment
        uses: ./.github/actions/toolchain_and_env

      - name: Build Yew App
        run: trunk build --release --dist ./dist --public-url ./

      - name: Copy index.html to 404.html
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy to gh-pages/production/
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: production
          keep_files: true
